server:
  port: 8083

spring:
  application:
    name: TWEET-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/twutter-tweet-service
    username: postgres
    password: cosu2362

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: false
    open-in-view: true

  sql:
    init:
      mode: never

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  devtools:
    remote:
      restart:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
