server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twitter_tweet
    username: postgres
    password: 1903
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: false
    open-in-view: true

  sql:
    init:
      mode: never

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
