server:
  port: 8084
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  application:
    name: TL-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

