server:
  port: 8084
spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  application:
    name: TIME-LINE-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

