server:
  port: 8080

spring:
  application:
    name: AUTH-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
  instance:
    hostname: localhost
