spring:
  cloud:
    gateway:
      routes:
        - id: security
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/**
          filters:
            - name: CustomFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CustomFilter
  application:
    name: spring-cloud-gateway-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
