spring:
#  cloud:
#    gateway:
#      routes:
#        - id: security
#          uri: lb://AUTH-SERVICE
#          filters:
#            - name: PreGatewayFilterFactory
#          predicates:
#            - Path=/twutter/**
#
#
#        - id: user-service
#          uri: lb://USER-SERVICE
#          filters:
#            - name: PreGatewayFilterFactory
#          predicates:
#            - Path=/twutter/users/**
  application:
    name: spring-cloud-gateway-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
