server:
  port: 9002

spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/twutter/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/twutter/**

        - id: TL-SERVICE
          uri: lb://TL-SERVICE
          predicates:
            - Path=/twutter/**

        - id: SG-SERVICE
          uri: lb://SG-SERVICE
          predicates:
            - Path=/twutter/**

        - id: TWEET-SERVICE
          uri: lb://TWEET-SERVICE
          predicates:
            - Path=/twitter/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true



#jwt:
#  secret: screte-value
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - mappings
#          - env
#          - health
#          - info
