server:
  port: 9002

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/twutter/**

        - id: BLOG-SERVICE
          uri: lb://BLOG-SERVICE
          predicates:
            - Path=/twutter/**

        - id: SOCIALGRAPH-SERVICE
          uri: lb://SOCIALGRAPH-SERVICE
          predicates:
            - Path=/twutter/**

        - id: TWEET-SERVICE
          uri: lb://SOCIALGRAPH-SERVICE
          predicates:
            - Path=/twitter/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: screte-value

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info