server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twutter_social_graph
    username: postgres
    password: cosu2362
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
